#!/usr/bin/env node
// Fetches the four OFL families as WOFF2 latin + latin-ext subsets from the
// Google Fonts API, stores them under fonts/<family>/ with each family's
// OFL.txt, and writes fonts.css with local() sources first.
// Run: node scripts/fetch-fonts.mjs   (no dependencies, Node 18+)
import { mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36';
const FAMILIES = [
  { dir: 'spectral', ofl: 'ofl/spectral', query: 'Spectral:ital,wght@0,400;0,500;0,600;1,400;1,500' },
  { dir: 'schibsted-grotesk', ofl: 'ofl/schibstedgrotesk', query: 'Schibsted+Grotesk:ital,wght@0,400..900;1,400..900' },
  { dir: 'source-serif-4', ofl: 'ofl/sourceserif4', query: 'Source+Serif+4:ital,opsz,wght@0,8..60,300..700;1,8..60,300..700' },
  { dir: 'ibm-plex-mono', ofl: 'ofl/ibmplexmono', query: 'IBM+Plex+Mono:wght@400;500' },
];
const KEEP = new Set(['latin', 'latin-ext']);
// A subset is a Modified Version under the OFL, and a Modified Version may not
// carry a Reserved Font Name. IBM Plex declares "Plex" as one, so its subset is
// served under another family name; local() still finds an installed original.
const ALIAS = { 'IBM Plex Mono': 'Satzspiegel Mono' };

const get = async (url, as = 'text') => {
  const res = await fetch(url, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return as === 'text' ? res.text() : Buffer.from(await res.arrayBuffer());
};
const sums = [];

let out = `/* fonts.css — Satzspiegel typefaces, self-hosted.
   Spectral, Schibsted Grotesk, Source Serif 4 and IBM Plex Mono are licensed
   under the SIL Open Font License 1.1; see fonts/<family>/OFL.txt.
   Latin and Latin Extended subsets. local() first, so an installed copy wins.
   IBM Plex Mono is served as "Satzspiegel Mono": the subset is a Modified
   Version under the OFL and may not use the Reserved Font Name "Plex".
   Generated by scripts/fetch-fonts.mjs. */\n`;
let bytes = 0, files = 0;

for (const fam of FAMILIES) {
  const dir = join(ROOT, 'fonts', fam.dir);
  await mkdir(dir, { recursive: true });
  const css = await get(`https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`);
  // Google writes the subset label as a comment immediately BEFORE each
  // @font-face block, so pair each comment with the block that follows it.
  const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
  if (blocks.length === 0) throw new Error('no labelled @font-face blocks for ' + fam.dir);
  let n = 0;
  for (const [, subset, b] of blocks) {
    if (!KEEP.has(subset)) continue;
    const family = b.match(/font-family:\s*'([^']+)'/)[1];
    const style = b.match(/font-style:\s*(\w+)/)[1];
    const weight = b.match(/font-weight:\s*([\d ]+)/)[1].trim();
    const stretch = (b.match(/font-stretch:\s*([^;]+);/) || [])[1];
    const range = b.match(/unicode-range:\s*([^;]+);/)[1];
    const url = b.match(/url\(([^)]+)\)/)[1];
    if (subset === 'latin' && !/U\+0000-00FF/.test(range)) throw new Error(`latin subset without basic Latin range in ${family}`);
    if (!/^https:\/\/fonts\.gstatic\.com\//.test(url)) throw new Error('unexpected font host: ' + url);
    const name = `${family.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${style}-${weight.replace(' ', '-')}-${subset}.woff2`;
    const buf = await get(url, 'buffer');
    if (buf.subarray(0, 4).toString('latin1') !== 'wOF2') throw new Error('not a WOFF2 file: ' + url);
    sums.push(`${createHash('sha256').update(buf).digest('hex')}  ${fam.dir}/${name}`);
    await writeFile(join(dir, name), buf); bytes += buf.length; files++; n++;
    const local = `local("${family}")` + (style === 'italic' ? `, local("${family} Italic")` : '');
    const served = ALIAS[family] || family;
    out += `\n@font-face {\n  font-family: "${served}";\n  font-style: ${style};\n  font-weight: ${weight};\n${stretch ? `  font-stretch: ${stretch};\n` : ''}  font-display: swap;\n  src: ${local}, url("fonts/${fam.dir}/${name}") format("woff2");\n  unicode-range: ${range};\n}\n`;
  }
  const ofl = await get(`https://raw.githubusercontent.com/google/fonts/main/${fam.ofl}/OFL.txt`);
  if (!/SIL OPEN FONT LICENSE/i.test(ofl)) throw new Error('OFL text not found for ' + fam.dir);
  await writeFile(join(dir, 'OFL.txt'), ofl);
  console.log(fam.dir, n, 'files');
}
await writeFile(join(ROOT, 'fonts.css'), out);
await writeFile(join(ROOT, 'fonts', 'SHA256SUMS'), sums.sort((a, b) => a.localeCompare(b)).join('\n') + '\n');
console.log(`fonts.css written: ${files} files, ${(bytes / 1024).toFixed(0)} KB`);
